version: "3.3"

services:

  db:
    image: mariadb:10.6
    restart: unless-stopped
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: proxy
